backend:
  name: git-gateway
  branch: master
media_folder: source/images
public_folder: /images
publish_mode: editorial_workflow
pages:
  enabled: true
  config:
    label: Page
    delete: false
    editor:
      preview: true
over_format: true
name: git-gateway
branch: master
collections:
  - name: all_posts
    fields: &ref_0
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: HH:mm:ss
        format: YYYY-MM-DD HH:mm:ss
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Categories
        name: categories
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Permalink
        name: permalink
        widget: string
        required: false
      - label: Comments
        name: comments
        widget: boolean
        default: true
        required: false
    label: Post
    folder: source/_posts
    create: true
    editor:
      preview: true
  - label: Page
    name: pages
    delete: false
    files:
      - name: about-index.md
        label: about
        file: source\about\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: admin-config.yml
        label: ''
        file: source\admin\config.yml
        editor:
          preview: true
        fields: *ref_0
      - name: admin-index.html
        label: ''
        file: source\admin\index.html
        editor:
          preview: true
        fields: *ref_0
